# mysql 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_room
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: jdbc
  security:
    user:
      name: root
      password: root

# sql日志打印 设置

